version: '3.8'

services:
  backend:
    image: oumaymabenbrahem/devops:latest  # Image Docker du backend
    container_name: backend-container
    restart: unless-stopped
    ports:
      - "8080:8080"  # Expose le port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpfoyerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb  # Assure que la base de données démarre avant le backend
    networks:
      - devops_network

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"  # Port exposé pour MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfoyerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops_network

networks:
  devops_network:

volumes:
  mysql_data:
