services:
  backend:
    image: oumaymabenbrahem/devops:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foyer-backend
    ports:
      - "8089:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - test
    depends_on:
      - mysqldb

  frontend:
    image: oumaymabenbrahem/angular_devops_ui:latest
    container_name: frontend-angular
    ports:
      - "4200:80"
    networks:
      - test
    depends_on:
      - backend

  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpfoyerdb
    ports:
      - "3307:3306"
    networks:
      - test
    volumes:
      - db:/var/lib/mysql

networks:
  test:
    driver: bridge

volumes:
  db:
