version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpfoyerdb
    ports:
      - "3307:3306"
    networks:
      - test
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  Foyer_Management:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: oumaymabenbrahem/devops:latest
    ports:
      - "9100:9100"  # Changed to match Dockerfile
    networks:
      - test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpfoyerdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

networks:
  test:

volumes:
  db:
