version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpfoyerdb
    ports:
      - "3307:3306"
    networks:
      - test
    volumes:
      - db:/var/lib/mysql

  Foyer_Management:
    depends_on:
      - mysqldb
    image: oumaymabenbrahem/devops:latest
    ports:
      - "8089:8089"
    networks:
      - test
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyerdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : null
          }'
      stdin_open: "true"  # Use string "true"
      tty: "true"  # Use string "true"

networks:
  test:

volumes:
  db: {}
